# PRACTICAL IMPLEMENTATION OF CREATING ARRAYS OF DIFFERENT DIMENSIONS ON NUMPY
## ZERO D-ARRAY

In [1]:
import numpy as np

In [3]:
a = np.array(55)

In [4]:
a

array(55)

In [5]:
type(a)

numpy.ndarray

In [6]:
a.ndim

0

## 1-D ARRAY
Definition: As stated in the video section that, a 1-D array is the collection of different zero dimension arrays and or the scalar values that we call in number

In [7]:
# To create a 1-D array we create a python list
b = np.array([1,2,3,4])

In [8]:
b

array([1, 2, 3, 4])

In [9]:
b.ndim

1

## 2-D ARRAY

In [10]:
c = np.array([[1,2,3],[7,8,9]])

In [11]:
c

array([[1, 2, 3],
       [7, 8, 9]])

In [12]:
c.ndim

2

## 3-D ARRAY

In [13]:
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [14]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [15]:
d.ndim

3

# SHAPE AND RESHAPE OF A NUMPY ARRAY
The shape of an array is the number of element in each dimension
### What is reshaping of an array?
- Reshaping means changing the shape of an array.
- The dimension of an array is the number of elements in each dimension
- By reshaping, we can add or remove dimensions or change number elements in each dimension.

In [20]:
#reshaping this numbers of array example
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [21]:
arr.shape

(2, 4)

### Reshaping 1-D  to 2-D Array

In [22]:
# Example converting the following 1-D array with 12 elements into a 2-D array. 
# The outermost dimension will have 4 arrays, each with 3 elements

In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#We will find the two numbers that when we multiply them will give 12
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Question: 
Can we reshape into any shape?

### Answer:
Yes, as long as the elements requiredd for reshaping are equal in both shapes.
We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3=9 elements..

### Flattening
Flattening means converting a multidimensional array into a 1D array.
We can use reshape (-1) to do this

In [25]:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## Practicals for Shape and Reshaping of an array

In [27]:
a = np.array([1,2,3,4,5])

# To check the shape of this array
a.shape

(5,)

In [29]:
# To show the same shape of 2-D array
b = np.array([[1,2,3,4],[5,6,7,8]]) 

In [30]:
b.shape

(2, 4)

In [31]:
# Reshaping the array
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [33]:
#To rehape c into two dimensions
new_arr = c.reshape(4,3)
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
new_arr.shape

(4, 3)

In [35]:
# Making c a 3-D array
new_arr2 = c.reshape(2,3,2)

In [36]:
new_arr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [37]:
new_arr2.shape

(2, 3, 2)

In [38]:
#To flatten any array take for example a twoDD_array
twoD_array = np.array([[1,2,3],[4,5,6]])

In [39]:
flatten_array = twoD_array.reshape(-1)

In [41]:
flatten_array

array([1, 2, 3, 4, 5, 6])

In [42]:
flatten_array.shape

(6,)

 # NUMPY ARRAY INDEXING
 ### Access Array Element
 Array indexing is the same as accessing an array element.
 You can access an array element by referring to its index number.
 The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second element has index 1 etc.

In [43]:
#This means calculating 3 + 4 as python index starts counting from 0
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


### Access 2-D Array
To access elements from 2-D arrays we can use comma separated integers representing the 
dimension and the index of te element.
Think of 2-D arrays like a table with two rows and columns, where the row represents the dimension and the index
represents the column.

#### Practical implementation

In [44]:
a = np.array([3,4,5,6])

In [45]:
a

array([3, 4, 5, 6])

In [46]:
a.ndim

1

In [47]:
a[0]

3

In [48]:
a[2]

5

In [49]:
a[2]+a[0]

8

#### For 2-D Array

To access any row containing any of the element

In [51]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [52]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
# Accessing elements from 2nd row and 5th column
b[1,4]

10

In [58]:
# Accessing elements from first row and 3rd column
b[0,2]

3

# Iterating NumPy Arrays
### Iterating Arrays
means going through elements one by one.
As we deal with multi-dimensional arrays in NumPy, we can do this using basic for loop python.
If we iterate on a 1-D array it will go through each element one by one.

In [61]:
# Iterating for a single 1-D array
arr = np.array([1,2,3,4])

In [62]:
for i in arr:
    print(i)

1
2
3
4


In [63]:
# Iterating for a 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])

In [66]:
for j in arr2:
    print(j)

[1 2 3]
[4 5 6]


In [67]:
# To access each and every element in arr
for j in arr2:
    for k in j:
        print(k)

1
2
3
4
5
6


# Array Slicing
### Slicing arrays:
Means taking elements from one give index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start : end : step].

If we don't pass start its considered 0

If we don't pass end its considered lenths of arry in that dimension

If we don't pass step its considered 1

In [68]:
a = np.array([1,2,3,4,5,6,7,8])

In [69]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
a[1:5]

array([2, 3, 4, 5])

In [74]:
a[2:7]
# Note that the element of the 0 list will not be printed and that of the 5 on the list too will not be printed

array([3, 4, 5, 6, 7])

In [73]:
a[4:]
# Means this index will print from index 4 to the end of the list

array([5, 6, 7, 8])

In [76]:
a[:5]
# This means the Numpy will print the list index from 0 to index 4 amd will omit 5

array([1, 2, 3, 4, 5])

In [77]:
a[1:6:2]
#This means that the list index will print 2 jump 3 print 4 jump 5 and print 6 

array([2, 4, 6])

#### Slice a 2-D Array

In [78]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [79]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [81]:
b[1,1:4]
#This means second row, 1 to 4

array([7, 8, 9])

In [83]:
b[0,0:3]
#This means first index from 0 index to the third index

array([1, 2, 3])

# NumPy Array Searching and Sorting
### Searching
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use where() method

### Sorting
Means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabeticeal, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [99]:
# Where operation
a = np.array([1,2,3,3,4,5,8,5,10,20,1])

In [100]:
x = np.where(a == 1)

In [101]:
y = np.where(a == 4)

In [102]:
x

(array([ 0, 10], dtype=int64),)

In [103]:
y

(array([4], dtype=int64),)

In [104]:
ans = np.where(a%2 == 0)

In [105]:
ans

(array([1, 4, 6, 8, 9], dtype=int64),)

In [106]:
# Sort Operation
np.sort(a)

array([ 1,  1,  2,  3,  3,  4,  5,  5,  8, 10, 20])

In [107]:
a2 = np.array([44,12,90,76,55])

In [108]:
np.sort(a2)

array([12, 44, 55, 76, 90])

In [109]:
# Example of arrays containing non-numerical values
a3 = np.array(["Mango", "Papara", "Apple", "Orange"])
np.sort(a3)

array(['Apple', 'Mango', 'Orange', 'Papara'], dtype='<U6')